title: DeCoster Design
author:
  name: Darryll A. DeCoster
  email: 'darryll@decoster.design'
metadata:
    description: 'Portfolio site of Darryll DeCoster. Interface, web and mobile design and development.'

